from app.agent.instruction.instructions import MANAGER_AGENT_INSTRUCTIONS, JUDGE_AGENT_INSTRUCTIONS, ANALYST_AGENT_INSTRUCTIONS

__all__ = ["MANAGER_AGENT_INSTRUCTIONS", "JUDGE_AGENT_INSTRUCTIONS", "ANALYST_AGENT_INSTRUCTIONS"]